// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFdGDJ9zWxbccIP--IL_RRb7BTk-e9LJQ',
    appId: '1:747679741182:web:ace1d92883d5b1ac3e61af',
    messagingSenderId: '747679741182',
    projectId: 'appmovil-2ebbf',
    authDomain: 'appmovil-2ebbf.firebaseapp.com',
    storageBucket: 'appmovil-2ebbf.firebasestorage.app',
    measurementId: 'G-W30BRC01DE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHp8zte6oSSNtDpumy_TTT45qCymdkLGo',
    appId: '1:747679741182:android:e30d5635d8dfadfb3e61af',
    messagingSenderId: '747679741182',
    projectId: 'appmovil-2ebbf',
    storageBucket: 'appmovil-2ebbf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx-WNJjsP6FZFLBVuneOYp5KtVds0Xdv4',
    appId: '1:747679741182:ios:a9810d7daa6789f83e61af',
    messagingSenderId: '747679741182',
    projectId: 'appmovil-2ebbf',
    storageBucket: 'appmovil-2ebbf.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx-WNJjsP6FZFLBVuneOYp5KtVds0Xdv4',
    appId: '1:747679741182:ios:a9810d7daa6789f83e61af',
    messagingSenderId: '747679741182',
    projectId: 'appmovil-2ebbf',
    storageBucket: 'appmovil-2ebbf.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFdGDJ9zWxbccIP--IL_RRb7BTk-e9LJQ',
    appId: '1:747679741182:web:f0cb22c462bbb35d3e61af',
    messagingSenderId: '747679741182',
    projectId: 'appmovil-2ebbf',
    authDomain: 'appmovil-2ebbf.firebaseapp.com',
    storageBucket: 'appmovil-2ebbf.firebasestorage.app',
    measurementId: 'G-D49ELRSSY0',
  );
}
